config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'

  resources :listings do
    post 'vote', on: :member
    post 'unvote', on: :member
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all

    cannot [:update, :destroy], [Listing, Voting] do |resource|
      if !user
        true
      elsif resource.user == user
        false
      else
        true
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :votings

  acts_as_commentable

  before_validation { self.user = User.current_user unless self.user}

  validates_presence_of :user, :name

  # TODO: thinking there should be a better way
  def vote_from(user)
    Voting.find_by(user:user, listing: self)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :votings
  has_many :listings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  cattr_accessor :current_user
end

app/models/voting.rb
class Voting < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing

  validates_uniqueness_of :listing_id, scope: :user

  # TODO: remove duplication in file `listing.rb`
  before_validation { self.user = User.current_user unless self.user}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter { User.current_user = current_user }
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  load_and_authorize_resource
end

app/controllers/listings_controller.rb
class ListingsController < BaseController

  before_action :authenticate_user!, :except => [:index]

  def index
    @listings = Listing.all
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # This method only handle pjax request
  def vote
    @voting = @listing.votings.build
    render_row_response {@voting.save}
  end

  def unvote
    @voting = @listing.vote_from(current_user)
    render_row_response {@voting.destroy}
  end

  private
    def render_row_response(&blk)
      respond_to do |f|
        if blk.call
          @replace = "listing-row-#{@listing.id}"
          @layout = 'row'
          f.html { redirect_to listing_path(@listing)}
          f.js { render 'replace_partial.js.erb' }
        else
          f.js { render js: 'alert("It does not work.. Tears.")' }
        end
      end
    end

    def listing_params
      params.require(:listing).permit(:name, :url, :description, :user_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BookVoting
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/listings/_form.html.slim
= form_for(@listing) do |f|
  - if @listing.errors.any?
    #error_explanation
      h2
        = pluralize(@listing.errors.count, "error")
        |  prohibited this listing from being saved:
      ul
        - @listing.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :url
    br
    = f.text_field :url
  .field
    = f.label :description
    br
    = f.text_area :description
  .actions
    = f.submit

app/views/listings/_row.slim
- listing ||= @listing
td
  = link_to listing.name, listing
td
  = listing.description
td
  = listing.votings.count
td
  = render 'voting_action', remote: true, listing: listing

td
  - if can?(:update, listing)
    = link_to 'Edit', edit_listing_path(listing)
td
  - if can?(:destroy, listing)
    = link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }

app/views/listings/_voting_action.slim
- if(current_user)
  - vote = listing.vote_from(current_user)
  - if vote
    - if can?(:destroy, vote)
      = link_to 'Unvote', unvote_listing_path(listing), method: :post, remote: remote
  - else
    - if can?(:create, Voting)
      = link_to 'Vote', vote_listing_path(listing), method: :post, remote: remote

app/views/listings/edit.html.slim
h1
  | Editing Listing
= render 'form'
= link_to 'Show', @listing
|  | 
= link_to 'Back', listings_path

app/views/listings/index.html.slim
p#notice
  = notice
h1
  | Book Listing
table
  thead
    tr
      th Name
      th Description
      th Votes
      th Action
      th[colspan="2"] Edit
  tbody
    - @listings.each do |listing|
      tr[id="listing-row-#{listing.id}"]
        = render 'row', listing: listing
br

- if current_user
  = link_to 'New Listing', new_listing_path
- else
  = link_to user_omniauth_authorize_path(:facebook), class: 'login-button facebook'
    = fa_icon 'facebook', class: 'left'
    | Facebook Login

app/views/listings/new.slim
h1
  | List a Book
= render 'form'
= link_to 'Back', listings_path

app/views/listings/replace_partial.js.erb
$('#<%= @replace %>' ).html('<%= escape_javascript(render (@layout)) %> ');

app/views/listings/show.html.slim
p#notice
  = notice
p
  strong Name:
  - if @listing.url.empty?
    = @listing.name
  - else
    = link_to @listing.name, @listing.url
p
  strong Description:
  = @listing.description
p
  strong Proposed By:
  = @listing.user.name

- voting_cnt = @listing.votings.count
p
  strong Votes:
  = voting_cnt

- if voting_cnt > 0
  p
    strong By:
    = @listing.votings.map {|v| "<span class='voting'>#{v.user.name}</span>"}.join(',').html_safe

= render 'voting_action', remote: false, listing: @listing

- if can? :update, @listing
  |  |
  = link_to 'Edit', edit_listing_path(@listing)

|  |
= link_to 'Back', listings_path